version: '2.1'
services:
  fcrepo_db:
    image: mysql:5
    ports:
      - '3306:3306'
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: fcrepo
    volumes:
      - fcrepo_db:/var/lib/mysql/
    healthcheck:
      test: mysql -h fcrepo_db -u root --password=root fcrepo --execute "SHOW DATABASES;"
      interval: 30s
      timeout: 30s
      retries: 5
  fcrepo:
    build: docker/fcrepo
    ports:
      - '8984:8984'
    depends_on:
      fcrepo_db:
        condition: service_healthy
    volumes:
      - fcrepo:/opt/fcrepo/data
volumes:
  fcrepo:
  fcrepo_db:
networks:
  default:
    driver: bridge
