version: '2.1'
services:
  web:
    build: docker/web
    image: hyrax_web
    ports:
      - "3000:3000"
    volumes:
      - ..:/opt/hyrax
      - gems:/opt/bundle
    depends_on:
      - db
      - db_test
      - redis
      - fcrepo
      - solr
    environment:
      RAILS_ENV: development
      HYRAX_DB_HOST: db
  worker:
    image: hyrax_web
    depends_on:
      - db
      - redis
      - web
    volumes_from:
      - web
    environment:
      RAILS_ENV: development
      HYRAX_REDIS_HOST: redis
      HYRAX_REDIS_PORT: 6379
      HYRAX_URL: http://web:3000
      QUEUE: "*"
    command: sidekiq
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: hyrax
    volumes:
      - pgdata:/var/lib/postgresql/data
  fcrepo_db:
    image: mysql:5
    ports:
      - "3306:3306"
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: fcrepo
    volumes:
      - fcrepo_db:/var/lib/mysql
    healthcheck:
      test: mysql -h fcrepo_db -u root --password=root fcrepo --execute "SHOW DATABASES;"
      interval: 30s
      timeout: 30s
      retries: 5
  db_test:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: hyrax
  redis:
    image: redis
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
  solr:
    build: docker/solr
    ports:
     - "8983:8983"
    volumes:
      - solr:/opt/solr/server/solr/mycores
  fcrepo:
    build: docker/fcrepo
    ports:
      - "8984:8984"
    depends_on:
      fcrepo_db:
        condition: service_healthy
    volumes:
      - fcrepo:/opt/fcrepo/data
volumes:
  fcrepo:
  fcrepo_db:
  gems:
  pgdata:
  redis:
  solr:
networks:
  default:
    driver: bridge
